create table Homework(
id integer generated by default as identity primary key ,
name varchar(50)  not null ,
description varchar(300) not null
);

create table Lesson(
id integer generated by default as identity primary key ,
name varchar(50)  not null ,
updatedAt timestamp default NOW() ,
homework_id integer ,
foreign key (homework_id) references Lesson(id)
);

create table Schedule(
id integer generated by default as identity primary key ,
name varchar(50)  not null ,
updatedAt timestamp default NOW() ,
lessons varchar(100) not null ,
lesson_id integer ,
foreign key (lesson_id) references Schedule(id)
);

create table lesson_schedule(
lesson_id integer REFERENCES lesson(id),
schedule_id integer REFERENCES schedule(id),
primary key (lesson_id, schedule_id)
);

select * from Homework;
select * from Lesson;
select * from Schedule;